"""Added created_id field in MeterType model

Revision ID: 8c7d0b1dc800
Revises: 3688d0a551cc
Create Date: 2021-10-19 17:14:28.098467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7d0b1dc800'
down_revision = '3688d0a551cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meter_type', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meter_type', 'created_at')
    # ### end Alembic commands ###
